### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by luandro** [digidem/mapeo-settings-builder#48]
Working a lot with configs and building micro-apps to facilitate the process of creating them, has gotten me dreaming a lot about possible paths for the settings builder. Some parts have been already built or startedthrough a few micro-apps:
- https://github.com/digidem/mapeo-config-renderer
- https://github.com/digidem/mapeo-config-translator
- https://github.com/digidem/mapeo-icons
- https://github.com/luandro/mapeo-config-deconstructor
- https://github.com/digidem/agroforest-mapeo-config-generator
- [generate-defaults scripts](https://gist.github.com/luandro/376465766129340bfddf21cf72b2c21f)

## Dreamed Features for V2:
The command-line interface (CLI) serves multiple purposes: it's a project generator, a first-time setup wizard, and a graphical user interface (GUI) for projects in either single or multiple languages.

The CLI launches a GUI that allows users to explore, identify errors, and modify the Mapeo presets either through natural language commands or direct interaction with each preset. The GUI also includes an icon finder for easy icon search.

The GUI provides the capability to trigger builds that automatically generate the `defaults.json` file and language translations from a CSV file. For users with Github, builds can also be triggered by pushing a commit, which is then automatically uploaded to the repository.

During the pre-installation phase, the following actions are performed:
  - [x] Project generation from a CSV file or Google Sheet (supports single or multiple languages)
  - [ ] Project generation from a template
  - [ ] Setting of project name and language
  - [ ] Automatic generation of metadata.json

During the editing phase, the following actions are performed:
  - Rendering of configuration in a web interface:
    - [x] Mobile GUI to display all icons, names, and borders
    - [ ] Mobile GUI to display form fields
    - [ ] Error display on GUI
  - [ ] File modification through natural language text chat
  - [ ] File modification through natural language audio commands
  - [ ] File modification (text, colors, icons) through GUI
  - [ ] File modification (fields) through GUI
  - [x] Icon search using the icon finder
  - [ ] Icon suggestions using the icon finder

During the build phase, the following actions are performed:
  - [ ] Build execution using GUI
  - [x] Translation generation
  - [x] Automatic generation of defaults.json
  - [ ] Version update

Builds can run on Github:
  - [ ] Display of instructions for creating a repository on Github
  - [x] Build and upload of settings file to Github upon git push

## Dreamed Features for V3:
- Web interface hosted in the cloud
- Config-builder service hosted in the cloud
- Native applications that can work offline

**Comment by gmaclennan** [comment]
@luandro now that we have https://github.com/digidem/comapeocat, maybe we can re-visit these ideas there and think about the future roadmap.
